### ISSUE TITLE
Using package sitar with hormone data? Getting error codes, please help!

### ISSUE THREAD

**Issue by dglassuw** [statist7/sitar#5]
Hello,

I am trying to run the following simple model before more complexity: 

model <- sitar(x = age, y = logT, id = id, data = hormonedata, df = 3)

where lotT = log of testosterone. The data do not have any NA's for this model, though when I log transformed there were some negative values. However, I keep getting errors such as "Error in nlme.formula(y ~ fitnlme(x, a, b, c, s1, s2, s3), fixed = s1 +  : 
  Singularity in backsolve at level 0, block 1" 
Or convergence issues. I am wondering if you can help? Are there any sitar examples using hormone data? 

Much appreciated!!

**Comment by statist7** [comment]
sitar is very fussy, and often throws errors like that. It needs sufficient data to detect the curve shape in individuals, so each subject needs multiple measurements, and there need to be some subjects with data covering most of the age range. What is the median number of measurements per subject, and the median age range, and the overall age range? 

You can simplify the model by specifying random = 'a+c' which omits the timing random effect. This is much more likely to fit, and doesn't need so much data. 

Also make sure there are no substantial outliers - they will also make the model hard to fit. So code like this is useful.
`model <- sitar(x = age, y = log(T), id = id, data = hormonedata, df = 3, random = 'a + c')`
note I have converted logT to log(T) - this allows plots in original testosterone units (though change T as necessary)
`plot.lme(model)` # to see residuals plotted against fitted values - anythiing outside ±4 is an outlier

**Comment by dglassuw** [comment]
I do not have a reliable pubertal stage, so am modeling across age for now. The data include participants ages 8-14 with 10-60 observations each. However, I am also working with a subset of the same data that has roughly 12 observations per participant as well. 

I will give the above a try and let you know how it goes

**Comment by dglassuw** [comment]
Ok thank you very much, that worked well. To plot the individual trajectories in one, I use mplot correct?

**Comment by statist7** [comment]
You can, but plot opt ‘u’ is more consistent with plot opt ‘a’ and ‘d’. 

Also you can use dfpower to optimise the df.
