### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by stevenbajer** [statist7/sitar#6]
Could you tell me about how to set or get the individal's three parameter in SITAR fomular in reality: Size, timing and intensity？ I want to use this model to estimate individual's height growth curves in reality!

Thanks a lot!

**Comment by statist7** [comment]
```
library(sitar)
m1 <- sitar(age, height, id, heights, 4)
ranef(m1)
```
You estimate the parameters size, timing and intensity for each individual by fitting the sitar model, and you access their random effects using ranef.

**Comment by stevenbajer** [comment]
Thank you very much. I also am a little worried if these three parameters I estimated for the specific child are not be in accord with the reality the child grow, the individual height growth curve calculated by SITAR formula maybe be very different with the factual height growth curves.

Could you give me some suggestions about how to estimate these three parameters more accurately? Maybe I can do some measurements to estimate these three parameters to get better height growth curves.

Thank you again!

**Comment by statist7** [comment]
SITAR uses data from a number of children to estimate a mean curve representing the height growth curve for the average child. The random effects then represent how each individual's growth curve differs from the mean curve.

I don't understand how you have estimated the three parameters, if you have not used SITAR.
