### ISSUE TITLE
Plotting sitar mean curves by group

### ISSUE THREAD

**Issue by dglassuw** [statist7/sitar#9]
Hello,

I attempted to plot mean curves by group according to your example (late v early menarche). The groups I am looking at are a group of infants who are exposed to HIV and those who are not exposed. See below code. Is there another way to plot the a and c parameters for both groups? Prior to making 'object' I made HEU/HUU status a factor variable called 'arm' where I have "HEU" below (where you had 'late' in your example) does it need to be the name of the factor var? 

object <- sitar(x = weeks, y= length_cm, id = ptid, data = sitar_fin_len, df=3,
                a.formula = ~HEU, c.formula = ~HEU)
## HUU group
plot(object, subset = HEU == FALSE, col = 4, lwd = 3,
     y2par = list(col = 4, lwd = 2), ylim = range(sitar_fin_len$length_cm))

## HEU group
lines(object, subset = HEU == TRUE, col = 2, lwd = 3,
      y2par = list(col = 2, lwd = 2))

## add legend
legend('right', paste(c('HUU', 'HEU'), 'Exposure Status'),
       lty = 1, col = c(4, 2), inset = 0.04)

**Comment by statist7** [comment]
Those plots are the default with opt = 'dv', i.e. mean distance and velocity curves. Your code is the correct way to plot such curves for multiple groups (I'm sorry it's clunky). The name (HEU in your case) in a.formula, c.formula and subset should be the name of the factor identifying the groups.

I'm not clear what you want to plot about the 'a' and 'c' parameters.

**Comment by dglassuw** [comment]
Ok so to clarify- a.formula = the variable name (e.g., status) and subset is the factor level?

I tried running this and it failed to converge sadly. It's odd because I can run the a+c sitar model with all the data, then subsetted by group but cannot figure out how to run/plot together with the above code.

**Comment by statist7** [comment]
I have experimented with the berkeley dataset, also in the sitar package, which has a similar design to your data, with measurements at ages 0, 0.085, 0.25,  0.5, 0.75 and 1.0. Fitting weight with random = 'a+b+c' it produces lots of warnings and the results don't make sense - plot( opt = 'a') shows much greater variation than it should.

Omitting the b random effect gives more sensible results, with varexp 79%., and it detects significantly greater size for males than females, adding a.formula = ~sex.

My guess is that sitar does not like datasets with just a few design ages - it prefers exact ages to provide more variability.

**Comment by dglassuw** [comment]
Ok thanks!
